### PR TITLE
Update opencl-amd.sh

### PR DESCRIPTION
**Pull request by PimpinPumpkin**
Many changes including critical bug fixes. Added functions to do with portable OpenGL, Davinci Resolve patching, and countless other improvements. See the changes in README.md for more explanation.

### CODE REVIEW

**Comment by sukhmeetbawa** [comment]
I thought davinci resolve worked? without pro opengl drivers because I was able to load it and select my gpu after installing OpenCL drivers is that not the case?

**Comment by sukhmeetbawa** [comment]
Alright

**Comment by sukhmeetbawa** [comment]
Why are you making the progl portable when it can be installed by amdgpu-install? That way it will always be updated also?

**Comment by PimpinPumpkin** [comment]
Because this way my system can still use the open source openGL drivers which perform better, but I can also run Resolve which requires the proGL drivers. The video I sent earlier explains that the performance of the proGL driver is worse in some situations.

If you installed the pro drivers with amdgpu-install, then that explains why you never had any issues with Resolve. I always have issues when my system uses switches completely to the amdgpu pro stack, hence this solution. 

In the future this set up could be more easily ported to other operating systems for on-click installation and configuration of Resolve.

**Comment by sukhmeetbawa** [comment]
Well according to [archwiki](https://wiki.archlinux.org/title/DaVinci_Resolvel) vega and above are supported. Since my laptop APU is vega based seems like progl wasn't required. So patching davinci resolve for Vega and up is not required i guess.

**Comment by PimpinPumpkin** [comment]
You're right. Either way, I believe performance in Resolve is better with the proGL drivers from what I've heard. Perhaps one of us should update the documentation to clarify that the patch isn't necesary for newer architectures. 

The rest of my Resolve patch fixes an audio delay issue by installing `alsa-plugins-pulseaudio`, and during install the user can choose an optional patch for UI scaling (I have a 4K display so it's mandatory for me).

**Pull request merged**
